#!/usr/bin/env bash
# Update package lists
sudo apt update

# Install Nginx
sudo apt-get -y install nginx

# Create directories and set permissions
sudo mkdir -p /var/www/InnVista.tech
sudo chmod -R 755 /var/www/InnVista.tech

# Create a simple HTML file
echo "Hello World!" | sudo tee /var/www/InnVista.tech/index.html

# Create an Nginx server block configuration file
sudo bash -c 'cat > /etc/nginx/sites-enabled/InnVista_config <<EOF
server {
    listen 80;
    listen [::]:80;

    root /var/www/InnVista.tech;
    index index.html;

    server_name InnVista.tech www.InnVista.tech;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF'

# Restart Nginx without using systemctl
sudo /etc/init.d/nginx restart
