#!/usr/bin/env bash
#command

sudo apt update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo chmod -R 755 /var/www/html/index.html
sudo echo "hello world!" >/var/www/html/index.html
sudo touch /etc/nginx/sites-enabled/default
sudo ufw allow 'Nginx HTTP'
# sudo echo "server {
#         listen 80;
#         listen [::]:80;

#         root  /var/www/html;

# }" >/etc/nginx/sites-enabled/default
# sudo service nginx restart
