#!/usr/bin/env bash
# script that adds configuration to redirect to innvista

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" /var/www/html/index.nginx-debian.html >sudo
sudo service nginx restart

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://google.com/;
    }
}" >default
