#!/usr/bin/env bash
#command
# shellcheck disable=SC2154

# Capture the hostname
#hostname=$(hostname)

# Install Nginx
sudo apt update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Configure Nginx with custom header
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    error_page 404 /custom_404.html;
    server_name $hostname;
    add_header X-Served-By $hostname;

    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location /redirect_me {
        return 301 http://google.com/;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
