#!/usr/bin/env bash
#command
# shellcheck disable= SC2154
sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;
	
	error_page 404 /custom_404.html;
    server_name 414302-web-02;
    add_header X-Served-By $server_name;

	location = /custom_404.html {
	root /usr/share/nginx/html;
	internal; 
    } 

    location /redirect_me {
        return 301 http://google.com/;
    }
}" >/etc/nginx/sites-available/default
sudo service nginx restart
