#!/usr/bin/env bash
#test commot
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install haproxy

printf %d "frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    option forwardfor
    server ubuntu1 100.25.169.190:8080 check
    server ubuntu2 34.239.255.200:8080 check" >>/etc/haproxy/haproxy.cfg
sudo service haproxy restart
