#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install haproxy

printf %s "
frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
	mode http
    server 414302-web-01 100.25.169.190:80 check
    server 414302-web-02 34.239.255.200:80 check" >>/etc/haproxy/haproxy.cfg
sudo service haproxy restart
