#!/usr/bin/env bash
sudo apt update
sudo apt install haproxy

printf %s "frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server server1  34.227.93.198:80 check
   server server2 54.166.169.232:80 check" >>/etc/haproxy/haproxy.cfg

sudo systemctl start haproxy
sudo systemctl enable haproxy
sudo systemctl restart haproxy
sudo systemctl reload haproxy
