#!/bin/bash
# Functions and parameters

DEFAULT=default # Default param value.

func2() {
	if [ -z "$1" ]; then                   # Is parameter #1 zero length?
		echo "-Parameter #1 is zero length.-" # Or no parameter passed.
	else
		echo "-Parameter #1 is \"$1\".-"
	fi

	variable=${1-$DEFAULT}      #  What does
	echo "variable = $variable" #+ parameter substitution show?
	#  ---------------------------
	#  It distinguishes between
	#+ no param and a null param.

	if [ "$2" ]; then
		echo "-Parameter #2 is \"$2\".-"
	fi

	return 0
}

func2
