#!/usr/bin/env bash
#makes a compressed archive of all sql databases
sudo mysqldump -u root -p"$1" --all-databases >backup.sql
current_date=$(date +"%d-%m-%Y")
tar -czvf "$current_date.tar.gz" ./backup.sql
