#!/usr/bin/env bash
mkdir -p /var/run              # Use -p to create parent directories if they don't exist
echo $$ >/var/run/myscript.pid # Use > to write the PID to the file

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT

while ((1)); do
	echo "To infinity and beyond"
	sleep 2
done

rm -r "/var"
