#!/usr/bin/env bash
#Bash script that:

PIDFILE="/var/run/myscript.pid"
touch $PIDFILE
echo $$ >$PIDFILE

trap 'echo I hate the kill command; rm $PIDFILE; kill -SIGKILL $$' SIGTERM
trap 'echo Y U no love me?!; kill -SIGKILL $$' SIGINT

trap 'rm $PIDFILE; kill -SIGKILL $$' SIGQUIT

while [ 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
