#!/usr/bin/env bash
#Bash script that:

touch "/var/run/myscript.pid"
echo $$ >"/var/run/myscript.pid"

trap 'echo I hate the kill command; rm /var/run/myscript.pid; kill -SIGKILL $$' SIGTERM
trap 'echo Y U no love me?!; kill -SIGKILL $$' SIGINT

trap 'rm /var/run/myscript.pid; kill -SIGKILL $$' SIGQUIT

while [ 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
