#!/usr/bin/env bash
# shellcheck disable=SC2009
bash_pid=$(pgrep bash)
kill -9 $bash_pid

# bash_pids=$(pidof bash)

# # Kill all of the bash processes.
# for bash_pid in $bash_pids; do
# 	if [ "$bash_pid" != "$$" ]; then
# 		kill -9 $bash_pid
# 	fi
# done
