#!/usr/bin/env bash
#Bash script that gives information about the school file.
# is_regular_file=0
# if test -f school; then
# 	echo "school file exists"
# 	is_regular_file=1
# else
# 	echo "school file does not exist"
# fi

# if [ -s school ]; then
# 	# The file is not-empty.
# 	echo "school file is not empty"
# else
# 	# The file is empty.
# 	echo "school file is empty"
# fi

# if ((is_regular_file == 1)); then
# 	echo "school is a regular file"
# fi
if [ -e "school" ]; then
	echo "school file exists"

	if [ -s "school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]; then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
