#!/usr/bin/env bash

# Append NAT rule to redirect traffic from port 8080 to port 80
sudo printf "%s\n" "*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT" | sudo tee -a /etc/ufw/before.rules

# Allow OpenSSH (port 22)
sudo ufw allow OpenSSH

# Allow SSH (port 22) from any source
sudo ufw allow 22/tcp

# Enable UFW firewall
sudo ufw enable

# Display the modified UFW configuration file
sudo cat /etc/ufw/before.rules
