#!/usr/bin/env bash
# script to add a new user to be able to configure ngnix settings
sudo adduser --system --no-create-home --disabled-login --disabled-password --group nginx

sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx

nginx_config="/etc/nginx/nginx.conf"
if [ ! -f "$nginx_config" ]; then
	echo "Nginx configuration file not found: $nginx_config"
	exit 1
fi
sudo sed -i 's/^user .*;/user nginx;/' "$nginx_config"
sudo sed -i '/listen[[:space:]]*80;/a \    listen 8080;' "$nginx_config"
sudo systemctl restart nginx
