#!/usr/bin/env bash
# Add nginx user if not already exists
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# Restart Nginx service
pkill apache2
# now start the nginx service with the new nginx user
sudo -u nginx service nginx start
